backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/media"
public_folder: "/public/work"
collections:
  - name: "work"
    label: "Work"
    folder: "src/work"
    create: true
    slug: "{{slug}}"
    fields:
    - { label: 'Layout', name: 'single', widget: 'hidden' }
      - { label: 'Meta Title', name: 'metaTitle', widget: 'string' }
      - { label: 'Meta Description', name: 'metaDescription', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Client Name', name: 'clientName', widget: 'string' }
      - { label: 'Project URL', name: 'projectUrl', widget: 'string' }
      - {
          label: 'Featured Image',
          name: 'featuredImg',
          widget: 'image',
          required: false
        }
      - { label: 'BG Color', name: 'bgColor', widget: 'color' }
      - { label: 'Featured', name: 'featured', widget: 'boolean' }
      - { label: 'Tasks', name: 'tasks', widget: 'list' }
      - { label: 'Project Year', name: 'year', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'date' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
